Ktls exceptions fix (#5)
Description: Change runtime exception to IOException for close notify so that it can be caught by the original code flow in linkedin-kafka.

JIRA Ticket: LIKAFKA-53806

Changes:

Changed RuntimeException thrown to IOException so that it can be caught by the original code path.

Testing:
```
2023/07/27 11:59:18.753 DEBUG [SslTransportLayer] [data-plane-kafka-network-thread-1-ListenerName(SSL)-SSL-15] [kafka-server] [] [SslTransportLayer channelId=10.32.113.199:16637-10.32.113.199:53954-0 key=channel=java.nio.channels.SocketChannel[connected local=/10.32.113.199:16637 remote=/10.32.113.199:53954], selector=sun.nio.ch.EPollSelectorImpl@294cf125, interestOps=1, readyOps=0] New SSL channel created with kernel offload turned on
2023/07/27 11:59:18.784 DEBUG [SslTransportLayer] [data-plane-kafka-network-thread-1-ListenerName(SSL)-SSL-15] [kafka-server] [] [SslTransportLayer channelId=10.32.113.199:16637-10.32.113.199:53954-0 key=channel=java.nio.channels.SocketChannel[connected local=/10.32.113.199:16637 remote=/10.32.113.199:53954], selector=sun.nio.ch.EPollSelectorImpl@294cf125, interestOps=1, readyOps=0] SSL handshake completed successfully with peerHost '10.32.113.199' peerPort 53954 peerPrincipal 'CN=vpraneet-ld1.linkedin.biz, OU=Tools, O=LinkedIn, L=Mountain View, ST=California, C=US' cipherSuite 'TLS_AES_256_GCM_SHA384'
2023/07/27 11:59:18.786 DEBUG [SslTransportLayer] [data-plane-kafka-network-thread-1-ListenerName(SSL)-SSL-15] [kafka-server] [] [SslTransportLayer channelId=10.32.113.199:16637-10.32.113.199:53954-0 key=channel=java.nio.channels.SocketChannel[connected local=/10.32.113.199:16637 remote=/10.32.113.199:53954], selector=sun.nio.ch.EPollSelectorImpl@294cf125, interestOps=1, readyOps=0] Kernel TLS enabled on socket on channel 10.32.113.199:16637-10.32.113.199:53954-0
2023/07/27 11:59:20.343 INFO [MetricsEventTrackerImpl] [pool-6-thread-1] [kafka-server] [] ServiceMetricsEvent: Event Count: 1 Sensor Count: 1055 Event Interval: 60000 Creation Time: 25 Send Time: 0 Total Time: 25}
2023/07/27 11:59:25.378 INFO [GroupCoordinator] [data-plane-kafka-request-handler-21] [kafka-server] [] [GroupCoordinator 1]: Preparing to rebalance group console-consumer-29631 in state PreparingRebalance with old generation 1 (__consumer_offsets-0) (reason: Removing member consumer-console-consumer-29631-1-095ae790-2a82-45f7-92bb-a222a9b4a441 on LeaveGroup)
2023/07/27 11:59:25.378 INFO [GroupCoordinator] [data-plane-kafka-request-handler-21] [kafka-server] [] [GroupCoordinator 1]: Group console-consumer-29631 with generation 2 is now empty (__consumer_offsets-0)
2023/07/27 11:59:25.379 INFO [GroupCoordinator] [data-plane-kafka-request-handler-21] [kafka-server] [] [GroupCoordinator 1]: Member MemberMetadata(memberId=consumer-console-consumer-29631-1-095ae790-2a82-45f7-92bb-a222a9b4a441, groupInstanceId=None, clientId=consumer-console-consumer-29631-1, clientHost=/10.32.113.199, sessionTimeoutMs=45000, rebalanceTimeoutMs=300000, supportedProtocols=List(range, cooperative-sticky)) has left group console-consumer-29631 through explicit `LeaveGroup` request
2023/07/27 11:59:25.845 DEBUG [SslTransportLayer] [data-plane-kafka-network-thread-1-ListenerName(SSL)-SSL-15] [kafka-server] [] [SslTransportLayer channelId=10.32.113.199:16637-10.32.113.199:53954-0 key=channel=java.nio.channels.SocketChannel[connected local=/10.32.113.199:16637 remote=/10.32.113.199:53954], selector=sun.nio.ch.EPollSelectorImpl@294cf125, interestOps=1, readyOps=0] Failed to send SSL Close message
java.io.IOException: Failed to send close_notify alert
	at com.linkedin.ktls.KernelTLSNativeHelper.sendCloseNotify(KernelTLSNativeHelper.java:113) ~[ktls-jni-1.0.2-SNAPSHOT.jar:?]
	at com.linkedin.ktls.KernelTls.closeNotify(KernelTls.java:32) ~[ktls-jni-1.0.2-SNAPSHOT.jar:?]
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:193) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:972) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:155) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:955) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at org.apache.kafka.common.network.Selector.close(Selector.java:939) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:625) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481) [kafka-clients-3.0.6-tlin-SNAPSHOT.jar:?]
	at kafka.network.Processor.poll(SocketServer.scala:998) [kafka_2.12-3.0.6-tlin-SNAPSHOT.jar:?]
	at kafka.network.Processor.run(SocketServer.scala:901) [kafka_2.12-3.0.6-tlin-SNAPSHOT.jar:?]
	at java.lang.Thread.run(Thread.java:829) [?:?]

```